### ISSUE TITLE
Information exposure through an exception

### ISSUE THREAD

**Issue by geekswagg** [DMGithinji/countpesa-server#1]
**Severity**: Medium
**Affected file/s** 
1. feedback/views.py:33
```
 31   except Exception as e:
 32       error_message = str(e)  # Convert the exception message to a string
 33       return JsonResponse({"status": "error", "message": error_message}, status=400)
```

# Explanation
Software developers often add stack traces to error messages, as a debugging aid. Whenever that error message occurs for an end user, the developer can use the stack trace to help identify how to fix the problem. In particular, stack traces can tell the developer more about the sequence of events that led to a failure, as opposed to merely the final state of the software when the error occurred.

# Recommendation
Send the user a more generic error message that reveals less information. Either suppress the stack trace entirely, or log it only on the server.

# Example
In the following example, an exception is handled in two different ways. In the first version, labeled BAD, the exception is sent back to the remote user by returning it from the function. As such, the user is able to see a detailed stack trace, which may contain sensitive information. In the second version, the error message is logged only on the server, and a generic error message is displayed to the user. That way, the developers can still access and use the error log, but remote users will not see the information.

```
from flask import Flask
app = Flask(__name__)

import traceback

def do_computation():
    raise Exception("Secret info")

## BAD
@app.route('/bad')
def server_bad():
    try:
        do_computation()
    except Exception as e:
        return traceback.format_exc()

## GOOD
@app.route('/good')
def server_good():
    try:
        do_computation()
    except Exception as e:
        log(traceback.format_exc())
        return "An internal error has occurred!"
```

# References
OWASP: [Improper Error Handling](https://owasp.org/www-community/Improper_Error_Handling).
Common Weakness Enumeration: [CWE-209](https://cwe.mitre.org/data/definitions/209.html).
Common Weakness Enumeration: [CWE-497](https://cwe.mitre.org/data/definitions/497.html).

**Comment by juanmilkah** [comment]
Agreed!

**Comment by juanmilkah** [comment]
Awesome, thanks for the update!
